#!/usr/bin/env bash
#call my numbers stevie wonder
i=0
while [ $i -le 19 ]
do
	((i++))
	case $i in
		4) echo -e "$i\nbad luck from China"
		;;
		9) echo -e "$i\nbad luck from Japan"
		;;
		17) echo -e "$i\nbad luck from Italy"
		;;
		*) echo "$i"
	esac
done




